apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: nginxexample.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx
              servicePort: 8080
