apiVersion: apps/v1
kind: Deployment
metadata:
  #namespace: mean
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
    spec:
      containers:
        - image: nau1/mean-nginx
          imagePullPolicy: IfNotPresent
          name: mean-nginx
          ports:
            - containerPort: 80
            - name: exporter
              containerPort: 9113
          resources: {}
      restartPolicy: Always
status: {}
