apiVersion: v1
kind: ConfigMap
metadata:
  name: probes
data:
  probes.yaml: |
    probes:
      CustomMetricsProbe:
      alias: angular-deployment.latency.probe
      location: 127.0.0.1
      type: java
      javaInfo:
          class: org.sa.rainbow.translator.probes.CustomMetricProbe
          period: 5000
          args.length: 5
          args.0: default
          args.1: angular-deployment
          args.2: selector?app=angular-deployment
          args.3: flask_http_request_duration_seconds_success_99p
          args.4: latency

      DeploymentPropertiesProbe:
        alias: deployments.votingapp.worker.probe
        location: 127.0.0.1
        type: java
        javaInfo:
          class: org.sa.rainbow.translator.probes.DeploymentInfoProbe
          period: 5000
          args.length: 2
          args.0: "default"
          args.1: "worker"
